/**
 * CypherGoat Exchange Plugin Chain Mapping
 *
 * CypherGoat is a swap AGGREGATOR: it quotes many underlying exchanges for one
 * pair and routes the trade to whichever one the caller picks.
 *
 * It identifies an asset by a (`coin`, `network`) pair of lowercase strings,
 * NOT by a contract address, and it exposes no public asset-list endpoint, so
 * both maps below are maintained by hand. See `docs/API_REQUIREMENTS.md`
 * sections 1 and 3 for the gaps that follow from this; they are the provider's
 * to close.
 *
 * Two maps are exported:
 *
 * - `cyphergoat`: the conventional Edge pluginId -> chain-code map, used for
 *   the cheap client-side gate before any network call.
 * - `cyphergoatAssets`: the authoritative per-asset table, keyed by Edge
 *   pluginId and then by EdgeTokenId. This is what the plugin resolves against.
 *
 * The per-asset table exists because CypherGoat's `network` is an asset-family
 * name rather than a chain: the same Edge chain can carry several different
 * CypherGoat `network` values (Ethereum alone spans `eth`, `link`, `shib`,
 * `usdc`, ...), and several chains CypherGoat serves are token-only, with no
 * native asset listed at all. A single chain-code map cannot express either.
 *
 * Resolving by tokenId rather than by currency code is also a safety property:
 * a user-added custom token whose currencyCode happens to be `USDT` does not
 * resolve, so it can never be quoted as if it were the real USDT.
 *
 * Every entry below was generated by cross-referencing CypherGoat's own coin
 * list against Edge's `builtinTokens`, so each tokenId is the exact string the
 * wallet passes in `EdgeSwapRequest`. Assets CypherGoat lists that Edge has no
 * builtin token for (Telcoin, LEO, the xStocks, BEP-20 USDT/DAI) are omitted
 * rather than guessed.
 */

import { EdgeTokenId } from 'edge-core-js/types'

import { EdgeCurrencyPluginId } from '../util/edgeCurrencyPluginIds'

/** A CypherGoat asset reference: the `coin` and `network` query parameters. */
export interface CypherGoatAsset {
  coin: string
  network: string
}

export const cyphergoat = new Map<EdgeCurrencyPluginId, string | null>()
cyphergoat.set('abstract', null)
// USDC only; CypherGoat lists no native ALGO.
cyphergoat.set('algorand', 'algo')
cyphergoat.set('amoy', null)
cyphergoat.set('arbitrum', null)
cyphergoat.set('avalanche', 'avax')
cyphergoat.set('axelar', null)
cyphergoat.set('badcoin', null)
// USDC only; CypherGoat lists no native ETH on Base.
cyphergoat.set('base', 'base')
cyphergoat.set('binance', null)
// CypherGoat splits BNB Smart Chain in two: native BNB is `bnb`,
// while every BEP-20 token on the same chain is `bsc`. The per-asset table
// below carries the real value; this chain code is only the native one.
cyphergoat.set('binancesmartchain', 'bnb')
cyphergoat.set('bitcoin', 'btc')
cyphergoat.set('bitcoincash', 'bch')
cyphergoat.set('bitcoincashtestnet', null)
cyphergoat.set('bitcoingold', null)
cyphergoat.set('bitcoingoldtestnet', null)
cyphergoat.set('bitcoinsv', null)
cyphergoat.set('bitcointestnet', null)
cyphergoat.set('bitcointestnet4', null)
cyphergoat.set('bobevm', null)
cyphergoat.set('botanix', null)
cyphergoat.set('calibration', null)
cyphergoat.set('cardano', 'ada')
cyphergoat.set('cardanotestnet', null)
cyphergoat.set('celo', null)
cyphergoat.set('coreum', null)
cyphergoat.set('cosmoshub', null)
cyphergoat.set('dash', 'dash')
cyphergoat.set('digibyte', null)
cyphergoat.set('dogecoin', 'doge')
cyphergoat.set('eboost', null)
cyphergoat.set('ecash', null)
cyphergoat.set('eos', null)
cyphergoat.set('ethDev', null)
// Several ERC-20s are listed by CypherGoat under a `network` equal to
// their own ticker (`link/link`, `shib/shib`, `aave/aave`, ...) rather than
// `eth`. The per-asset table below carries those; `eth` is the native code.
cyphergoat.set('ethereum', 'eth')
cyphergoat.set('ethereumclassic', 'etc')
cyphergoat.set('ethereumpow', null)
cyphergoat.set('fantom', null)
cyphergoat.set('feathercoin', null)
cyphergoat.set('filecoin', null)
cyphergoat.set('filecoinfevm', null)
cyphergoat.set('filecoinfevmcalibration', null)
cyphergoat.set('fio', null)
cyphergoat.set('groestlcoin', null)
cyphergoat.set('hedera', 'hbar')
cyphergoat.set('holesky', null)
cyphergoat.set('hyperevm', null)
cyphergoat.set('liberland', null)
cyphergoat.set('liberlandtestnet', null)
cyphergoat.set('litecoin', 'ltc')
cyphergoat.set('mayachain', null)
cyphergoat.set('monad', null)
cyphergoat.set('monero', 'xmr')
cyphergoat.set('nym', null)
cyphergoat.set('opbnb', null)
// USDC and DAI only; CypherGoat lists no native ETH on Optimism.
cyphergoat.set('optimism', 'op')
cyphergoat.set('osmosis', null)
cyphergoat.set('piratechain', 'arrr')
cyphergoat.set('pivx', null)
cyphergoat.set('polkadot', 'dot')
// CypherGoat lists no native POL, only Polygon tokens (`usdc/poly`,
// `usdt/poly`, `dai/poly`), so the per-asset table has no null-tokenId entry
// and a native-POL quote is rejected client-side.
cyphergoat.set('polygon', 'poly')
cyphergoat.set('pulsechain', null)
cyphergoat.set('qtum', null)
cyphergoat.set('ravencoin', null)
cyphergoat.set('ripple', 'xrp')
cyphergoat.set('robinhood', null)
cyphergoat.set('rsk', null)
cyphergoat.set('sepolia', null)
cyphergoat.set('smartcash', null)
cyphergoat.set('solana', 'sol')
cyphergoat.set('sonic', null)
cyphergoat.set('stellar', null)
cyphergoat.set('sui', 'sui')
cyphergoat.set('suitestnet', null)
cyphergoat.set('telos', null)
cyphergoat.set('tezos', 'xtz')
cyphergoat.set('thorchainrune', null)
cyphergoat.set('thorchainrunestagenet', null)
cyphergoat.set('ton', null)
// Native TRX is `trx`; TRC-20 tokens on the same chain are `tron`.
cyphergoat.set('tron', 'trx')
cyphergoat.set('ufo', null)
cyphergoat.set('vertcoin', null)
cyphergoat.set('wax', null)
cyphergoat.set('zano', 'zano')
cyphergoat.set('zcash', 'zec')
// Edge calls this chain `zcoin`; its asset and CypherGoat call it FIRO.
cyphergoat.set('zcoin', 'firo')
cyphergoat.set('zksync', null)

/**
 * Edge pluginId -> (EdgeTokenId -> CypherGoat asset). A `null` tokenId key is
 * the chain's native asset; its absence means CypherGoat does not list that
 * native asset, only tokens on the chain.
 */
export const cyphergoatAssets = new Map<
  EdgeCurrencyPluginId,
  Map<EdgeTokenId, CypherGoatAsset>
>()

// USDC only; CypherGoat lists no native ALGO.
cyphergoatAssets.set(
  'algorand',
  new Map<EdgeTokenId, CypherGoatAsset>([
    ['31566704', { coin: 'usdc', network: 'algo' }]
  ])
)

cyphergoatAssets.set(
  'avalanche',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'avax', network: 'avax' }] // native AVAX
  ])
)

// USDC only; CypherGoat lists no native ETH on Base.
cyphergoatAssets.set(
  'base',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [
      '833589fcd6edb6e08f4c7c32d4f71b54bda02913',
      { coin: 'usdc', network: 'base' }
    ]
  ])
)

// CypherGoat splits BNB Smart Chain in two: native BNB is `bnb`,
// while every BEP-20 token on the same chain is `bsc`. The per-asset table
// below carries the real value; this chain code is only the native one.
cyphergoatAssets.set(
  'binancesmartchain',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'bnb', network: 'bnb' }], // native BNB
    [
      '8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
      { coin: 'usdc', network: 'bsc' }
    ],
    [
      'e9e7cea3dedca5984780bafc599bd69add087d56',
      { coin: 'busd', network: 'bsc' }
    ]
  ])
)

cyphergoatAssets.set(
  'bitcoin',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'btc', network: 'btc' }] // native BTC
  ])
)

cyphergoatAssets.set(
  'bitcoincash',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'bch', network: 'bch' }] // native BCH
  ])
)

cyphergoatAssets.set(
  'cardano',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'ada', network: 'ada' }] // native ADA
  ])
)

cyphergoatAssets.set(
  'dash',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'dash', network: 'dash' }] // native DASH
  ])
)

cyphergoatAssets.set(
  'dogecoin',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'doge', network: 'doge' }] // native DOGE
  ])
)

// Several ERC-20s are listed by CypherGoat under a `network` equal to
// their own ticker (`link/link`, `shib/shib`, `aave/aave`, ...) rather than
// `eth`. The per-asset table below carries those; `eth` is the native code.
cyphergoatAssets.set(
  'ethereum',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'eth', network: 'eth' }], // native ETH
    [
      '514910771af9ca656af840dff83e8264ecf986ca',
      { coin: 'link', network: 'link' }
    ],
    [
      'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      { coin: 'usdc', network: 'usdc' }
    ],
    [
      'dac17f958d2ee523a2206206994597c13d831ec7',
      { coin: 'usdt', network: 'eth' }
    ],
    [
      '4fabb145d64652a948d72533023f6e7a623c7c53',
      { coin: 'busd', network: 'eth' }
    ],
    [
      '6b175474e89094c44da98b954eedeac495271d0f',
      { coin: 'dai', network: 'eth' }
    ],
    [
      '0000000000085d4780b73119b644ae5ecd22b376',
      { coin: 'tusd', network: 'tusd' }
    ],
    [
      '95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
      { coin: 'shib', network: 'shib' }
    ],
    [
      '7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
      { coin: 'aave', network: 'aave' }
    ],
    [
      '0d8775f648430679a709e98d2b0cb6250d2887ef',
      { coin: 'bat', network: 'bat' }
    ],
    [
      '056fd409e1d7a124bd7017459dfea2f387b6d5cd',
      { coin: 'gusd', network: 'gusd' }
    ],
    [
      '45804880de22913dafe09f4980848ece6ecbaf78',
      { coin: 'paxg', network: 'paxg' }
    ],
    [
      '2260fac5e5542a773aa44fbcfedf7c193bc2c599',
      { coin: 'wbtc', network: 'wbtc' }
    ],
    [
      '111111111117dc0aa78b770fa6a738034120c302',
      { coin: '1inch', network: '1inch' }
    ],
    [
      'f446aabf60f10c2f455f0a1728afdd48c653a5a3',
      { coin: 'fusd', network: 'fusd' }
    ]
  ])
)

cyphergoatAssets.set(
  'ethereumclassic',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'etc', network: 'etc' }] // native ETC
  ])
)

cyphergoatAssets.set(
  'hedera',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'hbar', network: 'hbar' }] // native HBAR
  ])
)

cyphergoatAssets.set(
  'litecoin',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'ltc', network: 'ltc' }] // native LTC
  ])
)

cyphergoatAssets.set(
  'monero',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'xmr', network: 'xmr' }] // native XMR
  ])
)

// USDC and DAI only; CypherGoat lists no native ETH on Optimism.
cyphergoatAssets.set(
  'optimism',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [
      '0b2c639c533813f4aa9d7837caf62653d097ff85',
      { coin: 'usdc', network: 'op' }
    ],
    ['da10009cbd5d07dd0cecc66161fc93d7c9000da1', { coin: 'dai', network: 'op' }]
  ])
)

cyphergoatAssets.set(
  'piratechain',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'arrr', network: 'arrr' }] // native ARRR
  ])
)

cyphergoatAssets.set(
  'polkadot',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'dot', network: 'dot' }] // native DOT
  ])
)

// CypherGoat lists no native POL, only Polygon tokens (`usdc/poly`,
// `usdt/poly`, `dai/poly`), so the per-asset table has no null-tokenId entry
// and a native-POL quote is rejected client-side.
cyphergoatAssets.set(
  'polygon',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [
      '3c499c542cef5e3811e1192ce70d8cc03d5c3359',
      { coin: 'usdc', network: 'poly' }
    ],
    [
      'c2132d05d31c914a87c6611c10748aeb04b58e8f',
      { coin: 'usdt', network: 'poly' }
    ],
    [
      '8f3cf7ad23cd3cadbd9735aff958023239c6a063',
      { coin: 'dai', network: 'poly' }
    ]
  ])
)

cyphergoatAssets.set(
  'ripple',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'xrp', network: 'xrp' }] // native XRP
  ])
)

cyphergoatAssets.set(
  'solana',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'sol', network: 'sol' }], // native SOL
    [
      'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      { coin: 'usdc', network: 'sol' }
    ],
    [
      'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      { coin: 'usdt', network: 'sol' }
    ]
  ])
)

cyphergoatAssets.set(
  'sui',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'sui', network: 'sui' }] // native SUI
  ])
)

cyphergoatAssets.set(
  'tezos',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'xtz', network: 'xtz' }] // native XTZ
  ])
)

// Native TRX is `trx`; TRC-20 tokens on the same chain are `tron`.
cyphergoatAssets.set(
  'tron',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'trx', network: 'trx' }], // native TRX
    ['TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8', { coin: 'usdc', network: 'tron' }],
    ['TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', { coin: 'usdt', network: 'tron' }],
    ['TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4', { coin: 'tusd', network: 'tron' }]
  ])
)

cyphergoatAssets.set(
  'zano',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'zano', network: 'zano' }] // native ZANO
  ])
)

cyphergoatAssets.set(
  'zcash',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'zec', network: 'zec' }] // native ZEC
  ])
)

// Edge calls this chain `zcoin`; its asset and CypherGoat call it FIRO.
cyphergoatAssets.set(
  'zcoin',
  new Map<EdgeTokenId, CypherGoatAsset>([
    [null, { coin: 'firo', network: 'firo' }] // native FIRO
  ])
)
