/**
 * Maps Edge `EdgeCurrencyPluginId` -> HoudiniSwap chain `shortName` (v2 `GET /chains`),
 * or `null` when Houdini has no compatible non-memo chain for that asset.
 *
 * Hand-authored for the HoudiniSwap prototype from the Phase 1 coverage matrix.
 * Memo-required chains (XRP/XLM/Cosmos-family) are intentionally `null` because the
 * prototype does not yet plumb a deposit memo / `destinationTag`.
 */

import { EdgeCurrencyPluginId } from '../util/edgeCurrencyPluginIds'

export const houdini = new Map<EdgeCurrencyPluginId, string | null>()
houdini.set('abstract', null)
houdini.set('algorand', 'algorand')
houdini.set('amoy', null)
houdini.set('arbitrum', 'arbitrum')
houdini.set('avalanche', 'avalanche')
houdini.set('axelar', null)
houdini.set('badcoin', null)
houdini.set('base', 'base')
houdini.set('binance', null)
houdini.set('binancesmartchain', 'bsc')
houdini.set('bitcoin', 'bitcoin')
houdini.set('bitcoincash', 'bitcoincash')
houdini.set('bitcoincashtestnet', null)
houdini.set('bitcoingold', null)
houdini.set('bitcoingoldtestnet', null)
houdini.set('bitcoinsv', 'bsv')
houdini.set('bitcointestnet', null)
houdini.set('bitcointestnet4', null)
houdini.set('bobevm', null)
houdini.set('botanix', null)
houdini.set('calibration', null)
houdini.set('cardano', 'cardano')
houdini.set('cardanotestnet', null)
houdini.set('celo', 'celo')
houdini.set('coreum', null)
houdini.set('cosmoshub', null)
houdini.set('dash', 'dash')
houdini.set('digibyte', null)
houdini.set('dogecoin', 'doge')
houdini.set('eboost', null)
houdini.set('ecash', 'eCash')
houdini.set('eos', null)
houdini.set('ethDev', null)
houdini.set('ethereum', 'ethereum')
houdini.set('ethereumclassic', null)
houdini.set('ethereumpow', null)
houdini.set('fantom', 'fantom')
houdini.set('feathercoin', null)
houdini.set('filecoin', null)
houdini.set('filecoinfevm', null)
houdini.set('filecoinfevmcalibration', null)
houdini.set('fio', null)
houdini.set('groestlcoin', null)
houdini.set('hedera', null)
houdini.set('holesky', null)
houdini.set('hyperevm', 'hyperevm')
houdini.set('liberland', null)
houdini.set('liberlandtestnet', null)
houdini.set('litecoin', 'litecoin')
houdini.set('mayachain', null)
houdini.set('monad', null)
houdini.set('monero', 'monero')
houdini.set('nym', null)
houdini.set('opbnb', 'opbnb')
houdini.set('optimism', 'optimism')
houdini.set('osmosis', null)
houdini.set('piratechain', null)
houdini.set('pivx', 'pivx')
houdini.set('polkadot', 'polkadot')
houdini.set('polygon', 'polygon')
houdini.set('pulsechain', 'pulsechain')
houdini.set('qtum', null)
houdini.set('ravencoin', null)
houdini.set('ripple', null)
houdini.set('rsk', 'rootstock')
houdini.set('sepolia', null)
houdini.set('smartcash', null)
houdini.set('solana', 'solana')
houdini.set('sonic', 'sonic')
houdini.set('stellar', null)
houdini.set('sui', 'sui')
houdini.set('suitestnet', null)
houdini.set('telos', 'telos')
houdini.set('tezos', null)
houdini.set('thorchainrune', null)
houdini.set('thorchainrunestagenet', null)
houdini.set('ton', null)
houdini.set('tron', 'tron')
houdini.set('ufo', null)
houdini.set('vertcoin', null)
houdini.set('wax', null)
houdini.set('zano', null)
houdini.set('zcash', 'Zcash')
houdini.set('zcoin', null)
houdini.set('zksync', 'zksync-era')
