/**
 * n.exchange Exchange Plugin Chain Mapping
 *
 * See https://api.n.exchange/en/api/v2/currency/ for list of supported currencies
 *
 * This file maps EdgeCurrencyPluginId -> n.exchange network identifier (or null)
 *
 * Supported networks: ALGO, ATOM, SOL, BCH, BTC, DASH, DOGE, DOT, EOS, TON,
 * HBAR, LTC, XLM, XRP, XTZ, ZEC, TRON, ADA, BASE, POL, ETH, AVAXC, BSC,
 * ETC, ARB, OP, FTM, SONIC, SUI, HYPE, FIL, XMR
 */

import { EdgeCurrencyPluginId } from '../util/edgeCurrencyPluginIds'

export const nexchange = new Map<EdgeCurrencyPluginId, string | null>()
nexchange.set('abstract', null)
nexchange.set('algorand', 'ALGO')
nexchange.set('amoy', null)
nexchange.set('arbitrum', 'ARB')
nexchange.set('avalanche', 'AVAXC')
nexchange.set('axelar', null)
nexchange.set('badcoin', null)
nexchange.set('base', 'BASE')
nexchange.set('binance', null)
nexchange.set('binancesmartchain', 'BSC')
nexchange.set('bitcoin', 'BTC')
nexchange.set('bitcoincash', 'BCH')
nexchange.set('bitcoincashtestnet', null)
nexchange.set('bitcoingold', null)
nexchange.set('bitcoingoldtestnet', null)
nexchange.set('bitcoinsv', null)
nexchange.set('bitcointestnet', null)
nexchange.set('bitcointestnet4', null)
nexchange.set('bobevm', null)
nexchange.set('botanix', null)
nexchange.set('cacao', null)
nexchange.set('calibration', null)
nexchange.set('cardano', 'ADA')
nexchange.set('cardanotestnet', null)
nexchange.set('celo', null)
nexchange.set('coreum', null)
nexchange.set('cosmoshub', 'ATOM')
nexchange.set('dash', 'DASH')
nexchange.set('digibyte', null)
nexchange.set('dogecoin', 'DOGE')
nexchange.set('eboost', null)
nexchange.set('ecash', null)
nexchange.set('eos', 'EOS')
nexchange.set('ethDev', null)
nexchange.set('ethereum', 'ETH')
nexchange.set('ethereumclassic', 'ETC')
nexchange.set('ethereumpow', null)
nexchange.set('fantom', 'FTM')
nexchange.set('feathercoin', null)
nexchange.set('filecoin', null)
nexchange.set('filecoinfevm', 'FIL')
nexchange.set('filecoinfevmcalibration', null)
nexchange.set('fio', null)
nexchange.set('groestlcoin', null)
nexchange.set('hedera', 'HBAR')
nexchange.set('holesky', null)
nexchange.set('hyperevm', 'HYPE')
nexchange.set('liberland', null)
nexchange.set('liberlandtestnet', null)
nexchange.set('litecoin', 'LTC')
nexchange.set('mayachain', null)
nexchange.set('monad', null)
nexchange.set('monero', 'XMR')
nexchange.set('nym', null)
nexchange.set('opbnb', null)
nexchange.set('optimism', 'OP')
nexchange.set('osmosis', null)
nexchange.set('piratechain', null)
nexchange.set('pivx', null)
nexchange.set('polkadot', 'DOT')
nexchange.set('polygon', 'POL')
nexchange.set('pulsechain', null)
nexchange.set('qtum', null)
nexchange.set('ravencoin', null)
nexchange.set('ripple', 'XRP')
nexchange.set('rsk', null)
nexchange.set('sepolia', null)
nexchange.set('smartcash', null)
nexchange.set('solana', 'SOL')
nexchange.set('sonic', 'SONIC')
nexchange.set('stellar', 'XLM')
nexchange.set('sui', 'SUI')
nexchange.set('suitestnet', null)
nexchange.set('telos', null)
nexchange.set('tezos', 'XTZ')
nexchange.set('thorchainrune', null)
nexchange.set('thorchainrunestagenet', null)
nexchange.set('ton', 'TON')
nexchange.set('tron', 'TRON')
nexchange.set('ufo', null)
nexchange.set('vertcoin', null)
nexchange.set('wax', null)
nexchange.set('zano', null)
nexchange.set('zcash', 'ZEC')
nexchange.set('zcoin', null)
nexchange.set('zksync', null)
